// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXTDJLZkOUJ2tCRPuRHbsrnoO5Z5tPahw',
    appId: '1:1030971242207:web:c5326da3b0bbaf89ca1b6a',
    messagingSenderId: '1030971242207',
    projectId: 'fire-notes-75f1a',
    authDomain: 'fire-notes-75f1a.firebaseapp.com',
    storageBucket: 'fire-notes-75f1a.appspot.com',
    measurementId: 'G-92JBK2CQ8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlAxnDjohLSnLfFIBe5GrfZKrt47PF-lY',
    appId: '1:1030971242207:android:843bab3824bc222aca1b6a',
    messagingSenderId: '1030971242207',
    projectId: 'fire-notes-75f1a',
    storageBucket: 'fire-notes-75f1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIsJGKvgIRBJPyt7NlcfVHy_HeFHnKmYE',
    appId: '1:1030971242207:ios:9cb0740f981d353cca1b6a',
    messagingSenderId: '1030971242207',
    projectId: 'fire-notes-75f1a',
    storageBucket: 'fire-notes-75f1a.appspot.com',
    iosClientId: '1030971242207-6qqr4q2kh5kimdtdrsril1653q1g0ggg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIsJGKvgIRBJPyt7NlcfVHy_HeFHnKmYE',
    appId: '1:1030971242207:ios:9cb0740f981d353cca1b6a',
    messagingSenderId: '1030971242207',
    projectId: 'fire-notes-75f1a',
    storageBucket: 'fire-notes-75f1a.appspot.com',
    iosClientId: '1030971242207-6qqr4q2kh5kimdtdrsril1653q1g0ggg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireNotes',
  );
}
